SELECT TOP 20 * FROM customer_behaviour


/*Q1. What is the total revenue generated by male vs. female customers? */
SELECT gender, sum(purchase_amount) as total_revenue
FROM customer_behaviour
GROUP BY gender
/* we will analysis across demographics. We want to compare revenue by gender because this will help  design better targeted compaign for each gender */


/* Q2. Which customers used a discount but still spent more than the average purchase amount? */

SELECT customer_id, purchase_amount FROM customer_behaviour
WHERE discount_applied = 'Yes' AND purchase_amount>(SELECT avg(purchase_amount) FROM customer_behaviour)
/* Q3. Which are the top 5 products with the highest average review rating? */
SELECT TOP 5 item_purchased,CAST(avg(review_rating) AS DECIMAL(4,2)) as avg_review_rating
FROM customer_behaviour
GROUP BY item_purchased
ORDER by avg_review_rating desc

-- We can highlight product with highest review rating in our marketing comaign and can be sold at premium price --

-- Q4. Compare the average purchase amounts between Standard and Express Shipping. --
SELECT shipping_type,AVG(purchase_amount) as average_purchase_amount
FROM customer_behaviour
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type
-- average_purchase_amount of Express is more so we will prefer Express more for fast delivery

/*Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers. */
SELECT subscription_status,COUNT(customer_id) as total_customers ,AVG(purchase_amount) as average_purchase_amount,SUM(purchase_amount) as Total_revenue
FROM customer_behaviour
GROUP BY subscription_status

-- Total revenue was higher than people who subscribed --

/*Q6. Which 5 products have the highest percentage of purchases with discounts applied? */
SELECT TOP 5 item_purchased,CAST(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)*100.0/COUNT(*) AS decimal(4,2)) AS discount_rate
FROM customer_behaviour
GROUP BY item_purchased
ORDER by discount_rate DESC
-- Discount rate tells us how often a product is sold with a discount. This helps us to see which product depend heavily on discount
-- High discount rate → Product needs discounts to sell, Low discount rate → Product sells well even without discounts --

/*Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. */
WITH customer_type as
( SELECT customer_id,previous_purchases,
  CASE WHEN previous_purchases = 1 Then 'New'
  WHEN previous_purchases BETWEEN 2 AND 10 Then 'Returning'
  ELSE 'Loyal' 
  END AS customer_segment
  FROM customer_behaviour
)

SELECT customer_segment, count(*) as 'No_of_customers'
FROM customer_type
GROUP BY customer_segment

-- We have more loyal customers --

/*Q8. What are the top 3 most purchased products within each category? */
WITH item_ranking as 
( SELECT category,item_purchased,count(customer_id) as 'no_of_customers_purchased',
  ROW_NUMBER() OVER(partition by category ORDER BY count(customer_id) DESC) as item_rank
  FROM customer_behaviour
  GROUP BY category,item_purchased
)

SELECT category,item_purchased,no_of_customers_purchased,item_rank
FROM item_ranking
WHERE item_rank<=3
 
-- We use ROW_NUMBER() when we want exactly top 3 rows,while DENSE_RANK() can return more than 3 rows if there are ties.--


/*Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?*/
SELECT subscription_status, count(customer_id) as no_of_repeat_buyers
FROM customer_behaviour
WHERE previous_purchases>5
GROUP BY subscription_status

-- large no. of repeat buyers are not subscribed
/* Q10. What is the revenue contribution of each age group? */
SELECT age_group,sum(purchase_amount) as Total_revenue
FROM customer_behaviour
GROUP BY age_group
order by Total_revenue DESC

SELECT COUNT(*) AS total_rows
FROM customer_behaviour